// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:963b11f8-cff6-4b04-ad47-502398bdc0fe',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'udogapp-hosting-mobilehub-2087013545',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd272ux5jxplovg.cloudfront.net',
    'aws_mobile_analytics_app_id': '45e5394bccc741f3924f78b164e622d9',
    'aws_project_id': 'aa89a59c-0e76-4bf6-92f4-5f5939b9beee',
    'aws_project_name': 'UdogApp',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'udogapp-mobilehub-2087013545',
}

export default awsmobile;
